import {v4 as uuidv4} from 'uuid';
const InsertData=()=>{
    const bookList=[ 
  {
    "bookId":uuidv4(),
    "title": "Alyssa: Echoes of the Forgotten Realm",
    "author": "Lamar Golden; Liana Golden",
    "yearOfPublish": 2006,
    "location":"C-2",
    "status":"available",
    "appliedBy":"",
    "department":"English",
    "publisher": "Castle Gate Releasing",
    "language": "English",
    "description": "Fantasy novel exploring a hidden realm and the journey of its heroine Alyssa toward reclaiming her destiny.",
    "imageUrl": "https://covers.openlibrary.org/b/id/12345678-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Golden Dilemma: Reunions and War",
    "author": "Lamar Golden",
    "yearOfPublish": 1998,
    "location":"C-2",
    "status":"available",
    "appliedBy":"",
    "department":"English",
    "publisher": "Unknown",
    "language": "English",
    "description": "A speculative fiction tale of political reunification and conflict in a divided empire.",
    "imageUrl": "https://covers.openlibrary.org/b/id/22334455-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Wild Animal: A Novel",
    "author": "Joël Dicker; Robert Bononno",
    "yearOfPublish": 1998,
    "location":"C-2",
    "status":"available",
    "appliedBy":"",
    "department":"English",
    "publisher": "Unknown",
    "language": "English",
    "description": "A psychological thriller tracing the hunt for a vanished conservationist deep in the Amazon.",
    "imageUrl": "https://covers.openlibrary.org/b/id/33445566-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Dream Girl Drama: A Novel",
    "author": "Tessa Bailey",
    "yearOfPublish": 1998,
    "location":"C-2",
    "status":"available",
    "appliedBy":"",
    "department":"English",
    "publisher": "Unknown",
    "language": "English",
    "description": "Romantic comedy featuring a celebrity couples chaotic journey back into the limelight.",
    "imageUrl": "https://covers.openlibrary.org/b/id/44556677-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Emperor of Gladness: A Novel",
    "author": "Ocean Vuong",
    "yearOfPublish": 1998,
    "location":"C-2",
    "status":"available",
    "appliedBy":"",
    "department":"Information Technology",
    "publisher": "Unknown",
    "language": "English",
    "description": "A lyrical coming-of-agetory reflecting on elder care and identity in small-town Connecticut.",
    "imageUrl": "https://covers.openlibrary.org/b/id/55667788-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Secret of Secrets",
    "author": "Dan Brown",
    "yearOfPublish": 2003,
    "location":"D-3",
    "status":"available",
    "appliedBy":"",
    "department":"Information Technology",
    "publisher": "Transworld Publishers",
    "language": "English",
    "description": "Robert Langdon races through ancient myths and a secret brotherhood in a quest around consciousness and lost civilizations.",
    "imageUrl": "https://covers.openlibrary.org/b/id/13472890-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Empire of AI: Dreams and Nightmares in Sam Altman's OpenAI",
    "author": "Karen Hao",
    "yearOfPublish": 2003,
    "location":"D-3",
    "status":"available",
    "appliedBy":"",
    "department":"Information Technology",
    "publisher": "Penguin Press",
    "language": "English",
    "description": "Investigative deep‑dive into OpenAIs culture, missions, and the broader implications of AGI.",
    "imageUrl": "https://covers.openlibrary.org/b/id/15948236-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Mark Twain",
    "author": "Ron Chernow",
    "yearOfPublish": 2003,
    "location":"D-3",
    "status":"available",
    "appliedBy":"",
    "department":"Information Technology",
    "publisher": "Penguin Press",
    "language": "English",
    "description": "Pulitzer‑level biography chronicling Twains life, writings, and legacy in American society.",
    "imageUrl": "https://covers.openlibrary.org/b/id/14012345-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Sunrise on the Reaping",
    "author": "Suzanne Collins",
    "yearOfPublish": 1987,
    "location":"A-3",
    "status":"available",
    "appliedBy":"",
    "department":"Chemistry",
    "publisher": "Scholastic",
    "language": "English",
    "description": "A dystopian prequel in the Hunger Games saga, focusing on Haymitch Abernathy during the 50th Hunger Games.",
    "imageUrl": "https://covers.openlibrary.org/b/id/15823728-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Why Not Build the Mosque",
    "author": "Dimitris Antoniou",
    "yearOfPublish": 1967,
    "location":"A-3",
    "status":"available",
    "appliedBy":"",
    "department":"Chemistry",
    "publisher": "Unknown",
    "language": "English",
    "description": "An analytical work examining the intersection of religion, politics, and minority rights in modern Greece.",
    "imageUrl": "https://covers.openlibrary.org/b/id/23456789-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Shattered Sky",
    "author": "Edward Krasinski; Joseph Krasinski; Miha Brumec; Rafael Andres",
    "yearOfPublish": 1967,
    "location":"A-3",
    "status":"available",
    "appliedBy":"",
    "department":"Human Resources",
    "publisher": "Unknown",
    "language": "English",
    "description": "A science fiction thriller that explores the consequences of a civilization discovering a fractured sky above their world.",
    "imageUrl": "https://covers.openlibrary.org/b/id/34567890-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "1984",
    "description": "A dystopian novel about totalitarianism, surveillance, and mind control.",
    "author": "George Orwell",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1949,
    "location":"A-2",
    "department":"Art & Design",
    "publisher": "Secker & Warburg",
    "language": "English",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "To Kill a Mockingbird",
    "description": "A novel about racial injustice in the Deep South during the 1930s.",
    "author": "Harper Lee",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1960,
    "location":"A-3",
    "department":"Art & Design",
    "publisher": "J.B. Lippincott & Co.",
    "language": "Spanish",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Great Gatsby",
    "description": "A story about the American dream, wealth, and lost love in the 1920s.",
    "author": "F. Scott Fitzgerald",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1925,
    "location":"A-4",
    "department":"Finance",
    "publisher": "Charles Scribner's Sons",
    "language": "German",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Moby-Dick",
    "description": "A narrative of the voyage of the whaling ship Pequod, led by Captain Ahab.",
    "author": "Herman Melville",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1851,
    "location":"A-5",
    "department":"Finance",
    "publisher": "Harper & Brothers",
    "language": "Hindi",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Brave New World",
    "description": "A dystopian novel that explores futuristic technological control over society.",
    "author": "Aldous Huxley",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1932,
    "location":"B-1",
    "department":"Finance",
    "publisher": "Chatto & Windus",
    "language": "Hindi",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Jane Eyre",
    "description": "A coming-of-age story of an orphaned girlss struggle for self-respect.",
    "author": "Charlotte Brontë",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1847,
    "location":"B-1",
    "department":"Human Resources",
    "publisher": "Smith, Elder & Co.",
    "language": "Hindi",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Frankenstein",
    "description": "The story of Victor Frankenstein and his monstrous creation.",
    "author": "Mary Shelley",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1818,
    "location":"B-1",
    "department":"Human Resources",
    "publisher": "Lackington, Hughes, Harding, Mavor & Jones",
    "language": "Hindi",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780141439471-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Catcher in the Rye",
    "description": "A teenage boys cynical view of the adult world and his journey through New York.",
    "author": "J.D. Salinger",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1951,
    "location":"B-1",
    "department":"Human Resources",
    "publisher": "Little, Brown and Company",
    "language": "Hindi",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Hobbit",
    "description": "The adventure of Bilbo Baggins as he joins a group of dwarves to recover treasure.",
    "author": "J.R.R. Tolkien",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1937,
    "location":"B-1",
    "department":"Information Technology",
    "publisher": "George Allen & Unwin",
    "language": "Telugu",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780261102217-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Fahrenheit 451",
    "description": "A dystopian future where books are banned and 'firemen' burn them.",
    "author": "Ray Bradbury",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1953,
    "location":"C-1",
    "department":"Information Technology",
    "publisher": "Ballantine Books",
    "language": "Telugu",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Picture of Dorian Gray",
    "description": "A man remains young while his portrait ages, reflecting his moral decay.",
    "author": "Oscar Wilde",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1890,
    "location":"C-1",
    "department":"Information Technology",
    "publisher": "Ward, Lock & Co.",
    "language": "Telugu",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Dracula",
    "description": "A vampire novel that introduced Count Dracula to the world.",
    "author": "Bram Stoker",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1897,
    "location":"C-1",
    "department":"Physics",
    "publisher": "Archibald Constable and Company",
    "language": "Telugu",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780141439846-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Wuthering Heights",
    "description": "A tragic tale of passion and revenge set on the Yorkshire moors.",
    "author": "Emily Brontë",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1847,
    "location":"C-1",
    "department":"Physics",
    "publisher": "Thomas Cautley Newby",
    "language": "Telugu",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Don Quixote",
    "description": "A comedic and philosophical tale of a man who imagines himself a knight.",
    "author": "Miguel de Cervantes",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1605,
    "location":"C-1",
    "department":"Physics",
    "publisher": "Francisco de Robles",
    "language": "Spanish",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780060934347-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "War and Peace",
    "description": "An epic novel of Russian society during the Napoleonic Era.",
    "author": "Leo Tolstoy",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1869,
    "location":"C-1",
    "department":"Compitetive",
    "publisher": "The Russian Messenger",
    "language": "Russian",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780199232765-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Les Misérables",
    "description": "The story of Jean Valjean and his quest for redemption.",
    "author": "Victor Hugo",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1862,
    "location":"D-1",
    "department":"Compitetive",
    "publisher": "A. Lacroix, Verboeckhoven & Cie",
    "language": "French",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780451419439-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Crime and Punishment",
    "description": "A psychological study of a man's descent into guilt and madness.",
    "author": "Fyodor Dostoevsky",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1866,
    "location":"E-1",
    "department":"Compitetive",
    "publisher": "The Russian Messenger",
    "language": "Russian",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780140449136-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Brothers Karamazov",
    "description": "A philosophical novel about faith, doubt, and morality.",
    "author": "Fyodor Dostoevsky",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1880,
    "location":"E-1",
    "department":"Science",
    "publisher": "The Russian Messenger",
    "language": "Russian",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Anna Karenina",
    "description": "The tragic love story of Anna and her affair with Count Vronsky.",
    "author": "Leo Tolstoy",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1878,
    "location":"E-1",
    "department":"Science",
    "publisher": "The Russian Messenger",
    "language": "Russian",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780143035008-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Count of Monte Cristo",
    "description": "A tale of revenge and justice after betrayal and imprisonment.",
    "author": "Alexandre Dumas",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1844,
    "location":"E-1",
    "department":"Science",
    "publisher": "Penguin Classics",
    "language": "French",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Divine Comedy",
    "description": "An allegorical journey through Hell, Purgatory, and Paradise.",
    "author": "Dante Alighieri",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1320,
    "location":"E-1",
    "department":"pharma",
    "publisher": "Various",
    "language": "Italian",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780142437223-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "One Hundred Years of Solitude",
    "description": "The multi-generational story of the Buendía family in Macondo.",
    "author": "Gabriel García Márquez",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1967,
    "location":"A-2",
    "department":"pharma",
    "publisher": "Harper & Row",
    "language": "Spanish",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Old Man and the Sea",
    "description": "A fishermans epic battle with a giant marlin in the Gulf Stream.",
    "author": "Ernest Hemingway",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1952,
    "location":"A-2",
    "department":"pharma",
    "publisher": "Charles Scribner's Sons",
    "language": "English",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780684801223-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Catch-22",
    "description": "A satirical war novel highlighting absurdities in military logic.",
    "author": "Joseph Heller",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1961,
    "location":"A-2",
    "department":"Chemistry",
    "publisher": "Simon & Schuster",
    "language": "English",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9781451626650-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Slaughterhouse-Five",
    "description": "A science fiction-infused anti-war novel by Kurt Vonnegut.",
    "author": "Kurt Vonnegut",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1969,
    "location":"A-2",
    "department":"Chemistry",
    "publisher": "Delacorte",
    "language": "Bengali",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780385333849-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Of Mice and Men",
    "description": "A story of two displaced migrant workers during the Great Depression.",
    "author": "John Steinbeck",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1937,
    "location":"A-2",
    "department":"Chemistry",
    "publisher": "Covici Friede",
    "language": "Bengali",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780140177398-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Lolita",
    "description": "The controversial story of obsession and manipulation.",
    "author": "Vladimir Nabokov",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1955,
    "location":"B-2",
    "department":"Culture & Tradition",
    "publisher": "Olympia Press",
    "language": "English",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780679723165-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Metamorphosis",
    "description": "A man wakes up to find himself transformed into a giant insect.",
    "author": "Franz Kafka",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1915,
    "location":"B-2",
    "department":"Culture & Tradition",
    "publisher": "Kurt Wolff Verlag",
    "language": "German",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780805210576-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "The Sound and the Fury",
    "description": "An experimental novel about the decline of a Southern family.",
    "author": "William Faulkner",
    "status":"available",
    "appliedBy":"",
    "yearOfPublish": 1929,
    "location":"B-2",
    "department":"Culture & Tradition",
    "publisher": "Jonathan Cape and Harrison Smith",
    "language": "Punjabi",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9780679732242-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Play, Learn and Explore: Space",
    "author": "Yoyo Books",
    "yearOfPublish": 1967,
    "location":"B-3",
    "status":"available",
    "appliedBy":"",
    "department":"Human Resources",
    "publisher": "Unknown",
    "language": "English",
    "description": "A childrens educational picture book introducing space concepts through playful activities and interactive pages.",
    "imageUrl": "https://covers.openlibrary.org/b/id/45678901-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Sunrise on the Reaping",
    "author": "Suzanne Collins",
    "yearOfPublish": 1967,
    "location":"B-3",
    "status":"available",
    "appliedBy":"",
    "department":"Human Resources",
    "publisher": "Scholastic",
    "language": "English",
    "description": "A dystopian prequel in the Hunger Games saga, focusing on Haymitch Abernathy during the 50th Hunger Games.",
    "imageUrl": "https://covers.openlibrary.org/b/id/15823728-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Stock Trader's Almanac 1967",
    "author": "Jeffrey A. Hirsch",
    "yearOfPublish": 2024,
    "location":"B-3",
    "status":"available",
    "appliedBy":"",
    "department":"Human Resources",
    "publisher": "Wiley & Sons, Incorporated",
    "language": "English",
    "description": "Comprehensive almanac guiding investors through cyclical patterns and historical market trends.",
    "imageUrl": "https://covers.openlibrary.org/b/id/14799241-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "UWorld Rxprep 2025 NAPLEX Course Book",
    "author": "UWorld",
    "yearOfPublish": 2024,
    "location":"B-3",
    "status":"available",
    "appliedBy":"",
    "department":"History",
    "publisher": "UWorld, LLC",
    "language": "English",
    "description": "Study guide for prospective pharmacists preparing for the 2025 NAPLEX examination.",
    "imageUrl": "https://covers.openlibrary.org/b/id/9876543-L.jpg"
  },
  {
    "bookId":uuidv4(),
    "title": "Empire of AI: Dreams and Nightmares in Sam Altman's OpenAI",
    "author": "Karen Hao",
    "yearOfPublish": 2025,
    "location":"B-3",
    "status":"available",
    "appliedBy":"",
    "department":"History",
    "publisher": "Penguin Press",
    "language": "English",
    "description": "In-depth narrative on OpenAIs rise, culture, and AGI ambitions, based on interviews and documents.",
    "imageUrl": "https://covers.openlibrary.org/b/id/15948236-L.jpg"
  }
];
    bookList.map( async (eachItem)=>{
             try {
                    const response=await fetch('http://localhost:5000/addBook',{
                                method:"POST",
                                headers:{
                                    "Content-Type":"application/json",
                                    Accept:"application/json"
                                },
                                body:JSON.stringify(eachItem)
                    });
                    console.log("inserted",eachItem.title);
                    
        } 
        catch (error) {
                   console.log(error)
                      }
        })
       
}
export default InsertData;

